// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jjlsdsgwaeadybbotwek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpqbHNkc2d3YWVhZHliYm90d2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTM3MTgsImV4cCI6MjA2NTQ4OTcxOH0.otqmvNxuoQds3g5CQvB85zCgSuWBDQoVTlz_EwEV7LE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);